Wxb2018/Wxb2018.Web/Controllers/DutyLogController.cs
using System;

using System.Web.Mvc;
using WXB.Bussiness.Common;
using WXB.Bussiness.Service;
using WXB.Bussiness.ViewModels;
using Wxb2018.Filters;

namespace Wxb2018.Controllers
{
    public class DutyLogController : BaseController
    {

        #region 获取值班记录
        /// <summary>
        /// 获取登录记录
        /// </summary>
        /// <returns></returns>
        [AdminFilter]
        public ActionResult Index()
        {
            try
            {
                PageVM<DutyLogVM> pageDuty = new DutyLogService().GetDutyLogPageData(new DutyLogQuery() { PageSize = 10 });

                if (pageDuty == null) pageDuty = new PageVM<DutyLogVM>();

                return View(pageDuty);
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

        #region 上班
        /// <summary>
        /// 上班
        /// </summary>
        /// <returns></returns>
        [BaseFilter]
        public ActionResult Add()
        {
            DutyLogVM vm = new DutyLogVM()
            {
                UserID = UserData.UserId,
                UserName = UserData.Name,
                StartTime = DateTime.Now
            };

            try
            {

                vm = new DutyLogService().AddDutyLog(vm);
                if (vm == null)
                {
                    return Json(new
                    {
                        Code = -400,
                        Msg = "参数错误"
                    });
                }

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleTypes = this.UserData.RoleTypes,
                    OperateTime = DateTime.Now,
                    OperateType = (int)EnumOperateType.上班
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString();
                Logger.AddLog(log);

                #endregion

                return Json(new
                {
                    Code = 200,
                    Msg = "添加成功",
                    Data = vm
                });
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

        #region 下班
        /// <summary>
        /// 下班
        /// </summary>
        /// <returns></returns>
        [BaseFilter]
        public ActionResult UpdateDutyStatus(DutyLogVM vm)
        {

            if (vm == null || !vm.ID.HasValue)
            {
                return Json(new
                {
                    Code = -400,
                    Msg = "参数错误"
                });
            }

            try
            {

                vm.EndTime = DateTime.Now;

                vm = new DutyLogService().UpdateDutyStatus(vm);
                if (vm == null)
                {
                    return Json(new
                    {
                        Code = -400,
                        Msg = "参数错误"
                    });
                }

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleTypes = this.UserData.RoleTypes,
                    OperateTime = DateTime.Now,
                    OperateType = (int)EnumOperateType.下班
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString();
                Logger.AddLog(log);

                #endregion

                return Json(new
                {
                    Code = 200,
                    Msg = "更新成功",
                    Data = vm
                });
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

        #region 获取当前登录用户的值班信息
        public ActionResult GetUserDutyLog()
        {
            try
            {
                if (UserData == null || !UserData.UserId.HasValue)
                {
                    return Json(new
                    {
                        Code = -401,
                        Msg = "请先登录"
                    }, JsonRequestBehavior.AllowGet);
                }

                OnDutyVM vm = new DutyLogService().GetUserDutyLog(UserData.UserId.Value);

                if (vm == null)
                {
                    return Json(new
                       {
                           Code = -200,
                           Msg = "暂无值班人员"
                       }, JsonRequestBehavior.AllowGet);
                }

                if (string.IsNullOrEmpty(vm.CurrentDutyUser) && vm.OtherDutyUser.Count > 0)
                {
                    return Json(new
                    {
                        Code = 201,
                        Msg = "当前用户还未值班，存在未标记下班的用户",
                        Data = vm
                    }, JsonRequestBehavior.AllowGet);
                }

                return Json(new
                {
                    Code = 200,
                    Msg = "当前用户正在值班",
                    Data = vm
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

        #region 获取值班记录(分页)
        /// <summary>
        /// 获取值班记录
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetDutyLogPageData(DutyLogQuery query)
        {
            if (query == null) query = new DutyLogQuery();

            if (!query.PageIndex.HasValue)
                query.PageIndex = 1;

            if (!query.PageSize.HasValue)
                query.PageSize = 10;

            try
            {
                PageVM<DutyLogVM> list = new DutyLogService().GetDutyLogPageData(query);

                if (list == null || list.Data == null || list.Data.Count == 0)
                {
                    return Json(new
                    {
                        Code = -200,
                        Msg = "暂无数据"
                    });
                }

                return Json(new
                {
                    Code = 200,
                    Msg = "获取成功",
                    Data = list
                });
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

    }
}

Wxb2018/Wxb2018.Web/Controllers/ResponseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WXB.Bussiness.Service;
using WXB.Bussiness.ViewModels;
using WXB.Bussiness.Common;
using WXB.Bussiness.Models;

namespace Wxb2018.Controllers
{
    public class ResponseController : BaseController
    {

        #region 获取响应状态
        /// <summary>
        /// 获取响应状态
        /// </summary>
        /// <returns></returns>
        public ActionResult GetResponseStatus()
        {
            try
            {
                ResponseStatusView resVM = new ResponseStatusService().GetResponseStatus();
                if (resVM == null)
                {
                    return Json(new { Code = -200, Msg = "暂无数据" }, JsonRequestBehavior.AllowGet);
                }

                if (resVM.EndTime.HasValue && DateTime.Now >= resVM.EndTime.Value.AddDays(1))
                {
                    resVM.Status = null;
                }
                else if (!resVM.EndTime.HasValue && resVM.StartTime.HasValue && DateTime.Now < resVM.StartTime)
                {
                    resVM.Status = null;
                }

                return Json(new
                {
                    Code = 200,
                    Msg = "获取成功",
                    Data = new
                    {
                        ID = resVM.ID,
                        Status = resVM.Status,
                        StatusText = resVM.Status.HasValue ? ((EnumResponseStatus)resVM.Status).ToString() : "--"
                    }
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }

        #endregion

        #region 编辑
        public ActionResult Edit(int responseId = 0)
        {
            try
            {
                ResponseStatusView vm = new ResponseStatusService().GetResponseStatusByID(responseId);
                if (vm == null) vm = new ResponseStatusView();
                return View("Edit", vm);
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }
        }
        #endregion

        #region 保存
        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        public ActionResult SaveResponse(ResponseStatusView vm)
        {

            if (vm == null)
            {
                return Json(new
                {
                    Code = -400,
                    Msg = "参数不能为空",
                });
            }

            try
            {
                ResponseStatusService rpSV = new ResponseStatusService();

                vm.Inputer = UserData.Name;
                vm.InputerID = UserData.UserId;

                if (vm.Status.HasValue && !vm.StartTime.HasValue && !vm.EndTime.HasValue)
                {
                    vm.StartTime = DateTime.Now;
                }

                vm = rpSV.SaveResponse(vm);

                #region 日志

                var log = new LogVM()
                {
                    Operator = this.UserData.Name,
                    OperatorID = this.UserData.UserId,
                    RoleTypes = this.UserData.RoleTypes,
                    OperateTime = DateTime.Now,
                    OperateType = (int)EnumOperateType.编辑
                };

                log.OperateDescribe = ((EnumOperateType)log.OperateType).ToString() + "响应状态";
                Logger.AddLog(log);

                #endregion

                if (vm.EndTime.HasValue && DateTime.Now >= vm.EndTime.Value.AddDays(1))
                {
                    vm.Status = null;
                }
                else if (!vm.EndTime.HasValue && vm.StartTime.HasValue && DateTime.Now < vm.StartTime)
                {
                    vm.Status = null;
                }

                return Json(new
                {
                    Code = 200,
                    Msg = "保存成功",
                    Data = new
                    {
                        ID = vm.ID,
                        Status = vm.Status,
                        StatusText = vm.Status.HasValue ? ((EnumResponseStatus)vm.Status).ToString() : "--"
                    }
                });
            }
            catch (Exception ex)
            {
                LogHelper.WriteLog(ex.Message);
                throw ex;
            }

        }
        #endregion
    }
}

Wxb2018/Wxb2018.Web/Views/Shared/AccountPartial.cshtml
<!-- 登录弹窗 -->
<div class="denglu-box center-1" id="login-Div">
    <div class="enter-2">
        <div class="title-close">登录<a class="closeBtn"></a></div>
        <form>
            <div class="error" id="lg-error">密码输入错误，请重新输入。</div>
            <ul>
                <li><input id="lg-userName" autocomplete="off" class="text-2" name="textfield" type="text" placeholder="请输入用户名" value="" /></li>
                <li><input id="lg-password" type="password" placeholder="请输入密码" class="password-2" /></li>
                <li class="ckbox" style="display:none;"><label><input id="lg-rememberMe" type="checkbox" /><em>记住密码</em></label></li>
            </ul>
        </form>
    </div>
</div>

Wxb2018/Wxb2018.Web/Views/Shared/LoginHeadPartial.cshtml
@using Wxb2018
@{
    WFFormPrincipal loginUser = User as WFFormPrincipal;
    if (loginUser == null)
    {
        loginUser = new WFFormPrincipal();
        loginUser.UserData = ViewBag.UserData as WFFormsAuthentication;
    }
    WFFormsAuthentication userInfo = loginUser == null ? new WFFormsAuthentication() : loginUser.UserData;
}

<div class="user-info">
    <em class="info-title">欢迎您,</em>
    <div class="info-name">
        <a href="javascript:void(0);" class="acc_name">
            <span>@(userInfo.Name)</span>
        </a>
        <ul class="info-account">
            <li><a href="@(Url.Action("logout", "account", new { redirectUrl=Url.Action("login","account") }))">退出</a></li>
        </ul>
    </div>
</div>

Wxb2018/Wxb2018.Web/Views/Shared/_Layout.cshtml
@using WXB.Bussiness.Common
@using Wxb2018
@{
    WFFormPrincipal loginUser = User as WFFormPrincipal;
    if (loginUser == null)
    {
        loginUser = new WFFormPrincipal();
        loginUser.UserData = ViewBag.UserData as WFFormsAuthentication;
    }

    WFFormsAuthentication userInfo = loginUser == null ? new WFFormsAuthentication() : loginUser.UserData;
    bool isLogin = userInfo == null ? false : true;
    bool isAdmin = (userInfo != null && userInfo.Flag == (int)EnumIsAdmin.是);

    //是否是'管理员或责编或总编'
    var maEditor = ((int)EnumRoleType.总编).ToString();
    var editor = ((int)EnumRoleType.责编).ToString();
    bool hasRight = isAdmin || (userInfo != null && !string.IsNullOrEmpty(userInfo.RoleTypes) && (userInfo.RoleTypes.Contains(maEditor) || userInfo.RoleTypes.Contains(editor)));

    bool hasRole = isAdmin || (userInfo != null && !string.IsNullOrEmpty(userInfo.RoleTypes));
}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <link href="~/content/css/common.css" rel="stylesheet" type="text/css" />
    <link href="~/content/css/base.css" rel="stylesheet" type="text/css" />
    <link href="~/content/iconfont/iconfont.css" rel="stylesheet" type="text/css" />
    <link href="~/content/plugins/pagination/pagination.css" rel="stylesheet" type="text/css" />
    @RenderSection("head", false)
    <script type="text/javascript" src="~/Content/plugins/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="~/Content/plugins/layer/layer.js"></script>
    <script type="text/javascript" src="~/Content/plugins/laydate/laydate.js"></script>
    <script type="text/javascript" src="~/Content/plugins/pagination/jquery.pagination.js"></script>
</head>
<body>

    <div class="topBar">
        <div class="mCon">
            <div class="topcon clearfix">

                @if (isLogin)
                {
                     <!--通知查询-->
                    <div class="home">
                        <a class="iconfont icon-notice"></a><a href="@Url.Action("Index", "Home")">通知查询</a>
                    </div>
                }

                @if (isLogin && isAdmin)
                {
                    <!--值班/登录记录-->
                    <div class="record">
                        <a class="record-text">
                            <span class="iconfont icon-record"></span><span>记录查询</span>
                        </a>
                        <ul class="record-type">
                            <li><a href="@Url.Action("index","dutylog")">值班记录</a></li>
                            <li><a href="@Url.Action("index","log")">登录记录</a></li>
                        </ul>
                    </div>
                }

                @if (isLogin)
                {
                    <!--响应状态-->
                    <div class="response">
                        <span class="response-text"><a class="iconfont icon-gear" href="javascript:void(0);" title="设置" style="@(hasRight?"":"display:none;")"></a><a class="response-icon">响应状态：</a></span><span class="response-val" data-status="1" data-id=""></span>
                    </div>

                       <!--值班-->
                    <div class="dutylog">
                        <span class="onduty-text">值班人员：</span><span class="onduty-names dutyuser ellipsis"></span>
                    </div>
                }

                @if (isLogin && hasRole)
                {
                     <!--打卡-->
                    <div class="punch" data-dutyid="">
                        <span class="iconfont icon-punchin show-font" title="上班打卡" style="display:none;"></span><span class="punchin-text" style="display:none;">上班打卡</span>
                        <span class="iconfont icon-punchout show-font" title="下班打卡" style="display:none;"></span><span class="punchout-text" style="display:none;">下班打卡</span>
                    </div>
                }

                <!--登录-->
                <div class="login">
                    <span>
                        <a href="javascript:void(0);" class="loginBtn denglu" id="btnconf">登录</a>
                    </span>
                </div>

            </div>
        </div>
    </div>

    <div class="main">
        @RenderBody()
    </div>

    <div>
        <input type="hidden" name="isLogin" value="@(isLogin)" />
        <input type="hidden" name="loginHeadPartialUrl" value="@Url.Action("LoginHeadPartial", "Account")" />
        <input type="hidden" name="accountPartialUrl" value="@Url.Action("AccountPartial", "Account")" />
        <input type="hidden" name="addDutyLogUrl" value="@Url.Action("Add", "DutyLog")" />
        <input type="hidden" name="updateDutyStatusUrl" value="@Url.Action("UpdateDutyStatus", "DutyLog")" />
        <input type="hidden" name="getUserDutyLogUrl" value="@Url.Action("GetUserDutyLog", "DutyLog")" />
        <input type="hidden" name="getResponseStatusUrl" value="@Url.Action("GetResponseStatus", "Response")" />
        <input type="hidden" name="editResponseUrl" value="@Url.Action("edit", "Response")" />
        <input type="hidden" name="saveResponseUrl" value="@Url.Action("SaveResponse", "Response")" />
        <input type="hidden" name="loginUrl" value="@Url.Action("Login", "Account")" />
    </div>
    <script type="text/javascript" src="~/Content/js/layout.js"></script>
    @RenderSection("scripts", false)
</body>
</html>